version: '3.9'

services:

  # ----------Infrastructure services----------

  # PostgreSQL database service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bento_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    
  # minio service
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    command: server --console-address ":9001"
    volumes:
      - minio_data:/data

  # ----------Application services----------
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - shared_data:/app/shared_data
    command: go run cmd/server/main.go
    profiles:
      - [app]
    depends_on:
      - postgres
      - redis

  ocr_worker:
    build: ./ocr_worker
    volumes:
      - shared_data:/app/shared_data
    profiles:
      - [app]
    depends_on:
      - redis




volumes:
  postgres_data:
  minio_data:
  shared_data: # The "RAM Disk" shared between Go and Python